# version: '3.8'

services:
  # 1. DATABASE SERVICE
  postgres:
    image: postgres:15-alpine
    container_name: todo_devops_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      # HOST_PORT:CONTAINER_PORT
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. BACKEND SERVICE
  backend:
    image: trandaine/devops-backend:latest
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: devops_backend
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=tododb
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  # 3. FRONTEND SERVICE
  frontend:
    image: trandaine/devops-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops_frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend

# Khai báo volume để dữ liệu database không bị mất khi tắt container
volumes:
  postgres_data: