# version: '3.8'

services:
  # 1. DATABASE SERVICE
  postgres:
    image: postgres:15-alpine
    container_name: devops_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      # HOST_PORT:CONTAINER_PORT
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. BACKEND SERVICE
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: devops_backend
    ports:
      - "8081:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

  # 3. FRONTEND SERVICE
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devops_frontend
    ports:
      - "3001:3000"

    # # OVERRIDE: Run the live development server instead of building static files
    # command: npm start
    # environment:
    #   # Tells React to actively poll for file changes across the Docker boundary
    #   - WATCHPACK_POLLING=true
    #   - CHOKIDAR_USEPOLLING=true
    # volumes:
    #   # LIVE LINK: Maps your local frontend folder directly into the container
    #   - ./frontend:/app
    #   # SAFETY NET: Prevents your local machine from overwriting the container's installed packages
    #   - /app/node_modules

    depends_on:
      - backend

# Khai báo volume để dữ liệu database không bị mất khi tắt container
volumes:
  postgres_data: