name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # TESTING BACKEND
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tododb
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d tododb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Initialize Database
        env:
          # psql automatically looks for this environment variable for the password
          PGPASSWORD: postgres 
        run: |
          until pg_isready -h 127.0.0.1 -p 5433 -U postgres; do
            echo "Waiting for Postgres to open TCP connections..."
            sleep 2
          done
          
          psql -h 127.0.0.1 -p 5433 -U postgres -d tododb -f ./database/database.sql

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: cd backend && npm ci

      - name: Run Tests
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5433
          DB_NAME: tododb
        run: cd backend && npm test

  # BUILD & PUSH DOCKER IMAGES
  build-and-push:
    name: Build and Push Images
    needs: test # This ensures tests MUST pass before building
    runs-on: ubuntu-latest
    
    # We only want to build and push when code is merged to main, not on PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-frontend:latest


# ---------------------------------------------------------
  # JOB 3: DEPLOY TO VPS
  # ---------------------------------------------------------
  deploy:
    name: Deploy to Production
    needs: build-and-push # Ensures we only deploy IF the build was successful
    runs-on: ubuntu-latest
    
    # Only deploy when pushing to the main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      

      # 2. SSH into the VPS and run Docker commands
      - name: Deploy to sever via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/wwwrootdev1/trandai-devops-project/devops-project-template
            
            sudo docker-compose down

            sudo git pull origin main

            sudo docker-compose pull

            sudo docker-compose up -d